pipeline:
  projectIdentifier: Jopa
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesHosted
            spec:
              identifier: k8s-hosted-infra
          execution:
            steps:
              - step:
                  type: Run
                  name: Echo Welcome Message
                  identifier: Echo_Welcome_Message
                  spec:
                    connectorRef: account.harnessImage
                    image: alpine
                    shell: Sh
                    command: echo "Welcome to Harness CI"
    - stage:
        name: ApproveJopa
        identifier: ApproveJopa
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: JopaApprove
                  identifier: JopaApprove
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups:
                        - account._account_all_users
                    approverInputs: []
        tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1684319597372
        repoName: sargsyan1986/python
        build: <+input>
  identifier: Build_python_1684321207772_Clone
  tags: {}
  name: Build python - Clone
  allowStageExecutions: true
